export const list = [
	{ name: 'País' },
	{ name: 'Afeganistão' },
	{ name: 'África do Sul' },
	{ name: 'Akrotiri' },
	{ name: 'Albânia' },
	{ name: 'Alemanha' },
	{ name: 'Andorra' },
	{ name: 'Angola' },
	{ name: 'Anguila' },
	{ name: 'Antárctida' },
	{ name: 'Antígua e Barbuda' },
	{ name: 'Arábia Saudita' },
	{ name: 'Arctic Ocean' },
	{ name: 'Argélia' },
	{ name: 'Argentina' },
	{ name: 'Arménia' },
	{ name: 'Aruba' },
	{ name: 'Ashmore and Cartier Islands' },
	{ name: 'Atlantic Ocean' },
	{ name: 'Austrália' },
	{ name: 'Áustria' },
	{ name: 'Azerbaijão' },
	{ name: 'Baamas' },
	{ name: 'Bangladeche' },
	{ name: 'Barbados' },
	{ name: 'Barém' },
	{ name: 'Bélgica' },
	{ name: 'Belize' },
	{ name: 'Benim' },
	{ name: 'Bermudas' },
	{ name: 'Bielorrússia' },
	{ name: 'Birmânia' },
	{ name: 'Bolívia' },
	{ name: 'Bósnia e Herzegovina' },
	{ name: 'Botsuana' },
	{ name: 'Brasil' },
	{ name: 'Brunei' },
	{ name: 'Bulgária' },
	{ name: 'Burúndi' },
	{ name: 'Butão' },
	{ name: 'Cabo Verde' },
	{ name: 'Camarões' },
	{ name: 'Camboja' },
	{ name: 'Canadá' },
	{ name: 'Catar' },
	{ name: 'Cazaquistão' },
	{ name: 'Chade' },
	{ name: 'Chile' },
	{ name: 'China' },
	{ name: 'Chipre' },
	{ name: 'Clipperton Island' },
	{ name: 'Colômbia' },
	{ name: 'Comores' },
	{ name: 'Congo-Brazzaville' },
	{ name: 'Congo-Kinshasa' },
	{ name: 'Coral Sea Islands' },
	{ name: 'Coreia do Norte' },
	{ name: 'Coreia do Sul' },
	{ name: 'Costa do Marfim' },
	{ name: 'Costa Rica' },
	{ name: 'Croácia' },
	{ name: 'Cuba' },
	{ name: 'Curacao' },
	{ name: 'Dhekelia' },
	{ name: 'Dinamarca' },
	{ name: 'Domínica' },
	{ name: 'Egipto' },
	{ name: 'Emiratos Árabes Unidos' },
	{ name: 'Equador' },
	{ name: 'Eritreia' },
	{ name: 'Eslováquia' },
	{ name: 'Eslovénia' },
	{ name: 'Espanha' },
	{ name: 'Estados Unidos' },
	{ name: 'Estónia' },
	{ name: 'Etiópia' },
	{ name: 'Faroé' },
	{ name: 'Fiji' },
	{ name: 'Filipinas' },
	{ name: 'Finlândia' },
	{ name: 'França' },
	{ name: 'Gabão' },
	{ name: 'Gâmbia' },
	{ name: 'Gana' },
	{ name: 'Gaza Strip' },
	{ name: 'Geórgia' },
	{ name: 'Geórgia do Sul e Sandwich do Sul' },
	{ name: 'Gibraltar' },
	{ name: 'Granada' },
	{ name: 'Grécia' },
	{ name: 'Gronelândia' },
	{ name: 'Guame' },
	{ name: 'Guatemala' },
	{ name: 'Guernsey' },
	{ name: 'Guiana' },
	{ name: 'Guiné' },
	{ name: 'Guiné Equatorial' },
	{ name: 'Guiné-Bissau' },
	{ name: 'Haiti' },
	{ name: 'Honduras' },
	{ name: 'Hong Kong' },
	{ name: 'Hungria' },
	{ name: 'Iémen' },
	{ name: 'Ilha Bouvet' },
	{ name: 'Ilha do Natal' },
	{ name: 'Ilha Norfolk' },
	{ name: 'Ilhas Caimão' },
	{ name: 'Ilhas Cook' },
	{ name: 'Ilhas dos Cocos' },
	{ name: 'Ilhas Falkland' },
	{ name: 'Ilhas Heard e McDonald' },
	{ name: 'Ilhas Marshall' },
	{ name: 'Ilhas Salomão' },
	{ name: 'Ilhas Turcas e Caicos' },
	{ name: 'Ilhas Virgens Americanas' },
	{ name: 'Ilhas Virgens Britânicas' },
	{ name: 'Índia' },
	{ name: 'Indian Ocean' },
	{ name: 'Indonésia' },
	{ name: 'Irão' },
	{ name: 'Iraque' },
	{ name: 'Irlanda' },
	{ name: 'Islândia' },
	{ name: 'Israel' },
	{ name: 'Itália' },
	{ name: 'Jamaica' },
	{ name: 'Jan Mayen' },
	{ name: 'Japão' },
	{ name: 'Jersey' },
	{ name: 'Jibuti' },
	{ name: 'Jordânia' },
	{ name: 'Kosovo' },
	{ name: 'Kuwait' },
	{ name: 'Laos' },
	{ name: 'Lesoto' },
	{ name: 'Letónia' },
	{ name: 'Líbano' },
	{ name: 'Libéria' },
	{ name: 'Líbia' },
	{ name: 'Listenstaine' },
	{ name: 'Lituânia' },
	{ name: 'Luxemburgo' },
	{ name: 'Macau' },
	{ name: 'Macedónia' },
	{ name: 'Madagáscar' },
	{ name: 'Malásia' },
	{ name: 'Malávi' },
	{ name: 'Maldivas' },
	{ name: 'Mali' },
	{ name: 'Malta' },
	{ name: 'Marianas do Norte' },
	{ name: 'Marrocos' },
	{ name: 'Maurícia' },
	{ name: 'Mauritânia' },
	{ name: 'México' },
	{ name: 'Micronésia' },
	{ name: 'Moçambique' },
	{ name: 'Moldávia' },
	{ name: 'Mónaco' },
	{ name: 'Mongólia' },
	{ name: 'Monserrate' },
	{ name: 'Montenegro' },
	{ name: 'Namíbia' },
	{ name: 'Nauru' },
	{ name: 'Navassa Island' },
	{ name: 'Nepal' },
	{ name: 'Nicarágua' },
	{ name: 'Níger' },
	{ name: 'Niue' },
	{ name: 'Noruega' },
	{ name: 'Nova Caledónia' },
	{ name: 'Nova Zelândia' },
	{ name: 'Omã' },
	{ name: 'Pacific Ocean' },
	{ name: 'Países Baixos' },
	{ name: 'Palau' },
	{ name: 'Panamá' },
	{ name: 'Papua-Nova Guiné' },
	{ name: 'Paquistão' },
	{ name: 'Paracel Islands' },
	{ name: 'Paraguai' },
	{ name: 'Peru' },
	{ name: 'Pitcairn' },
	{ name: 'Polinésia Francesa' },
	{ name: 'Polónia' },
	{ name: 'Porto Rico' },
	{ name: 'Portugal' },
	{ name: 'Quénia' },
	{ name: 'Quirguizistão' },
	{ name: 'Quiribáti' },
	{ name: 'Reino Unido' },
	{ name: 'República Centro-Africana' },
	{ name: 'República Dominicana' },
	{ name: 'Roménia' },
	{ name: 'Ruanda' },
	{ name: 'Rússia' },
	{ name: 'Salvador' },
	{ name: 'São Tomé e Príncipe' },
	{ name: 'São Vicente e Granadinas' },
	{ name: 'Sara Ocidental' },
	{ name: 'Seicheles' },
	{ name: 'Senegal' },
	{ name: 'Serra Leoa' },
	{ name: 'Sérvia' },
	{ name: 'Singapura' },
	{ name: 'Sint Maarten' },
	{ name: 'Síria' },
	{ name: 'Somália' },
	{ name: 'Southern Ocean' },
	{ name: 'Spratly Islands' },
	{ name: 'Sri Lanca' },
	{ name: 'Suazilândia' },
	{ name: 'Sudão' },
	{ name: 'Sudão do Sul' },
	{ name: 'Suécia' },
	{ name: 'Suíça' },
	{ name: 'Suriname' },
	{ name: 'Svalbard e Jan Mayen' },
	{ name: 'Tailândia' },
	{ name: 'Taiwan' },
	{ name: 'Tajiquistão' },
	{ name: 'Tanzânia' },
	{ name: 'Território Britânico do Oceano Índico' },
	{ name: 'Territórios Austrais Franceses' },
	{ name: 'Timor Leste' },
	{ name: 'Togo' },
	{ name: 'Tokelau' },
	{ name: 'Tonga' },
	{ name: 'Trindade e Tobago' },
	{ name: 'Tunísia' },
	{ name: 'Turquemenistão' },
	{ name: 'Turquia' },
	{ name: 'Tuvalu' },
	{ name: 'Ucrânia' },
	{ name: 'Uruguai' },
	{ name: 'Usbequistão' },
	{ name: 'Vaticano' },
	{ name: 'Venezuela' },
	{ name: 'Vietname' },

];
